import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { Pill } from 'lucide-react';

export function ProphecyModal() {
  const [isOpen, setIsOpen] = useState(false);

  const prophecyText = `The Light Pill Prophecy: A 29-Night Journey Into the Unknown

In the hidden corners of the digital realm, where blockchain cryptography meets ancient mystical traditions, twenty-nine artifacts were discovered by those who dared to look beyond the surface of reality. They called them Light Pills—animated portals, each containing the essence of a unique cosmic entity, waiting to be awakened by those brave enough to seek them. These are not mere collectibles to be bought and sold like ordinary tokens on the endless sea of digital marketplaces. They are keys to experiences, invitations to rituals that have waited centuries for the right moment to manifest, gateways to transformations that reshape not just digital wallets but the very souls of those who participate. And now, after countless cycles of the moon watching over a world that had forgotten its own magic, they have found their way to you.

Imagine twenty-nine beings, each with a name that echoes through forgotten corridors of consciousness, each with a personality as distinct as the phases of the moon, each with a purpose that transcends the simple act of collection. The Silent Witness, whose power lies in absolute observation, demanding complete silence from all who would seek its wisdom. The Dream Weaver, who reveals the intricate fabric of dreams and requires the mystical hour of midnight for its rituals to unfold properly. The Shadow Dancer, who teaches the ancient language of darkness and will only reveal its secrets on nights when the moon hides its face entirely. The River Singer, who speaks the forgotten tongue of flowing water and must be approached near streams where the water has flowed for millennia. The Fire Keeper, who holds within its animated form the memory of ancient flames and asks only for a single candle in return for its warmth. These five are merely the beginning, for twenty-four other mystical beings await discovery, each carrying within them a universe of meaning, each demanding a specific ritual for their power to be unlocked, each promising a revelation that cannot be found anywhere else in the vast expanse of human experience.

Every Light Pill carries within its digital DNA a collection of attributes that make it utterly unique in all the worlds, both physical and digital. There is the aura that surrounds it like a mist of colored light, invisible to ordinary eyes but palpable to those who have learned to sense such things. There is an energy level that ranges from dormant, like a seed waiting for spring, to blazing like a star at the moment of its birth. There is a rarity tier that places it somewhere between common and legendary, though those who truly understand know that rarity in the conventional sense means nothing compared to the uniqueness of each individual experience. There is an elemental alignment that connects it to earth, air, fire, water, or that mysterious fifth element that some call void and others call the space between worlds. There is a whispered message encoded in its metadata, a secret that reveals itself only to its holder at the precise moment of ritual completion. There is a ritual instruction, precise and demanding, that must be followed exactly for the transformation to occur. There is a fashion code that prescribes what to wear, which accessories to bear, how to present oneself before the ancient forces that the Light Pill summons. And there is an atmospheric setting, a specific location where the ritual must unfold, for place matters as much as intention in the work of transformation.

When you hold a Light Pill, you do not simply own an image that lives on a blockchain, validated by thousands of computers around the world. You own a night, a specific night in a cycle of twenty-nine that mirrors the cycle of the moon as it waxes and wanes through the months of our human calendar. The prophecy that accompanies these artifacts speaks of a twenty-nine night cycle, one night for each pill, one leader for each ritual, one transformation for each soul brave enough to participate in the full journey from beginning to end. Those who complete all twenty-nine nights report that they are never quite the same afterward, that something shifts in their perception of reality, that they carry with them always a sense that the world is more mysterious, more layered, more alive than they had previously imagined possible.

Consider how the nights unfold when the cycle is properly observed. On the first night, dedicated to the Silent Witness, the group gathers in an old house whose walls echo with decades of accumulated whispers from generations of inhabitants who have long since passed into memory. No one speaks for the duration of the ritual, which lasts exactly one hour measured by the slow burning of a specially prepared candle. In that hour of enforced silence, they simply observe each other, the way shadows move across faces in the candlelight, the dust dancing in moonbeams that penetrate through dusty windows, the subtle communications that pass between human beings when the crutch of language is removed. The holder of the Silent Witness wears a simple black robe with a hood that casts their face into shadow, revealing only the glint of eyes when the candle flares. At the stroke of midnight, they light the ritual candle and break the hour of silence with exactly three words spoken in a voice that seems to come from somewhere else entirely: "I have seen." And in that moment, something passes between all participants, a recognition that they have indeed seen something, though none can quite put words to what it was.

On the seventh night, when the Shadow Dancer takes its turn in the cycle, the group ascends to a rooftop under the new moon when darkness is absolute and the stars reveal themselves with unusual clarity. Everyone wears black clothing that absorbs rather than reflects light, and their faces are painted with subtle silver-gray patterns that seem to float independent of the features beneath them. The ritual itself involves a slow, silent dance where each participant mirrors another's movements with such precision that after a time, it becomes impossible to tell who is leading and who is following. As the dance continues into the depths of night, participants report feeling the presence of something ancient watching from the darkness beyond the rooftop's edge, something that has been there since before humans walked the earth and will remain long after we are gone.

On the fifteenth night, the River Singer calls the group to a very different kind of location. They gather beside a flowing stream, removing their shoes and feeling the cool smoothness of stones worn round by millennia of water passing over them. The leader wears flowing fabric in shades of blue and green that seem to move even when there is no wind, and their ankles are adorned with small bells that chime with each step in a rhythm that gradually synchronizes with the sound of the water. They teach the others to hear what ordinary ears miss, how different currents in the stream carry different meanings, how the water remembers every shore it has ever touched and shares those memories with those patient enough to listen. Each participant releases a small offering into the current, a flower perhaps, or a wish written on biodegradable paper, trusting the river to carry their intention to wherever such things need to go.

On the twenty-second night, the Dream Weaver transforms an ordinary room into something far more mysterious. The space is filled with candles of varying heights and sizes, their flames reflected in small mirrors placed strategically around the room, and soft cushions cover every surface where someone might sit or lie. Everyone wears sleep masks embroidered with mystical symbols that have been passed down through traditions too old to trace, and the leader wraps themselves in shawls threaded with silver that catch the candlelight in ways that seem impossible. They guide a collective meditation that blurs the line between wakefulness and dream so effectively that participants later struggle to remember which parts of their experience happened in the room and which happened in the landscapes of their own minds. When they share their visions afterward, strange synchronicities emerge, details that could not have been known to multiple people appearing in multiple accounts, suggesting that something real was indeed visited, something that exists beyond individual consciousness.

On the twenty-ninth and final night, the Void Walker presides over the completion of the cycle. The group gathers in a circular space that has been prepared for weeks, a space that contains nothing but darkness and a single flame at the exact center. Everyone wears black from head to toe, their faces veiled so that even the most basic human recognition becomes impossible. The ritual is a collective journey into silence, into nothingness, into the space between spaces where all Light Pills were born before they took form as animated images and metadata on a blockchain. When the candle finally burns out, plunging the circle into absolute darkness, something shifts. Those who have walked through all twenty-nine nights understand that they have changed, though the change may take months or even years to fully reveal itself. The cycle is complete, but the journey has only begun.

Behind all of this mystery, there is code, there is structure, there is technology that makes the magic possible while remaining invisible to those who experience only the ritual itself. The repository that contains the Light Pills holds twenty-nine animated GIFs, each one a unique mystical animation stored in a directory that waits for someone to upload its contents to the permanent web. It holds twenty-nine metadata JSON files, each containing structured data for one pill, data that includes names and descriptions and attributes and, most importantly, the ritual instructions that bring the whole experience to life. And it holds a React gallery, a dark gothic minimal interface built with modern web technologies that can display all twenty-nine pills in a way that honors their mystery while making them accessible to human perception.

The metadata for each pill follows a specific format that the blockchain can understand, a format that bridges the gap between human meaning and machine processing. It names the pill and describes its essence in words that humans can read. It points to an image stored on IPFS, the permanent web where content lives beyond the control of any single corporation or government. It lists attributes that can be used for filtering and sorting and discovering connections between pills. And it contains properties that go beyond what the blockchain typically tracks, properties like the specific ritual instructions, the whispered message that only the holder will hear, the attire that must be worn during the ritual, all the details that transform a digital token into a living experience.

Deploying the Light Pills is not a matter of simply buying and holding. It is an act of creation, of taking raw materials and shaping them into something that can actually function in the world. The process begins with preparing the offerings, reviewing the GIFs and metadata, understanding what each one contains before taking any further steps. It continues with ascending to IPFS, uploading the files to services like Pinata or NFT.Storage where they will remain accessible indefinitely, updating the metadata with the IPFS hashes that result from this upload so that each pill points to its own unique location on the permanent web. It requires forging the vessel, creating an ERC-721 smart contract using tools like OpenZeppelin and deploying it to a blockchain network that can support the weight of this endeavor, whether Ethereum mainnet or Polygon or Arbitrum or any of the other EVM-compatible chains that have emerged to carry such projects. Only after the contract is deployed and configured to point to the IPFS metadata can the twenty-nine Light Pills finally be minted into existence, born onto the blockchain where they will live as long as the networks themselves survive.

Then comes the opening of the gallery, running the React application locally or deploying it to services like Vercel or Netlify where anyone with the address can view the collection in all its dark glory. And finally, after all the technical work is complete, the cycle can begin. Participants can be invited, roles can be assigned, rituals can be followed, and the transformations that the Light Pills promise can actually unfold in the lives of real human beings gathering in real locations, wearing real clothing, performing real actions that carry meaning far beyond what any code could capture.

The locations where these rituals unfold matter enormously, for place is not merely a backdrop but an active participant in the work of transformation. Abandoned places like old houses and ruins and cellars carry the energy of all who have passed through them, making them suitable for pills like the Silent Witness and the Shadow Dancer and the Memory Keeper. Water sites like riverbanks and lakeshores and fountains carry the living memory of the water cycle that has sustained life on this planet for billions of years, making them perfect for the River Singer and the Tear Catcher and the Reflection Gazer. Fire spaces like fireplaces and campfires and candlelit rooms carry the transformative power that has fascinated humans since we first learned to control flame, making them appropriate for the Fire Keeper and the Ember Child and the Ash Collector. Natural sanctuaries like forests and gardens and mountains carry the ancient wisdom of the living earth, making them ideal for the Earth Mother and the Root Speaker and the Leaf Whisperer. Sacred architecture like temples and old churches and libraries carries the accumulated intention of all who built them and worshipped in them and sought knowledge within their walls, making them suitable for the Void Walker and the Time Weaver and the Knowledge Seeker. Urban edges like rooftops and abandoned factories and alleys carry the strange energy of human civilization in transition, making them perfect for the City Ghost and the Neon Dreamer and the Street Prophet. And interior ritual spaces, specially decorated rooms prepared with intention over days or weeks, carry the focused energy of the group that will occupy them, making them ideal for the Dream Weaver and the Shadow Painter and the Candle Dancer.

In these rituals, what you wear is not merely a matter of personal expression but a crucial element of the transformation itself. The Silent Witness demands a long black robe with a hood that can be raised to cast the face in shadow, a silver pendant in the form of an unbroken circle representing the cycle of observation, bare feet or simple leather sandals that connect the wearer directly to the earth, and a face half-veiled in shadow so that the observer becomes somewhat invisible even as they observe others. The Dream Weaver requires loose flowing fabrics in deep blue and silver that suggest the fluid nature of dreams, a sleep mask embroidered with moon phases that will be used during the meditation, rings on every finger numbering at least seven to represent the layers of dreaming consciousness, and hair worn loose and unbound to allow dreams to flow freely through the mind. The River Singer calls for flowing fabrics in shades of aquamarine and green that echo the colors of water in different lights, anklets with small bells or shells that chime with each step in imitation of water sounds, bare feet with soles washed in river water before the ritual begins, and a single water lily placed in the hair as an offering to the spirits of the stream. The Fire Keeper demands deep reds and oranges in fabrics that move like flame when the wearer moves, copper or brass jewelry that conducts heat in ways that seem almost magical, a face painted with subtle orange lines that suggest the patterns of fire, and a small candle always carried as a reminder of the fire that burns within all living things. The Shadow Dancer requires all black form-fitting clothing that absorbs rather than reflects light, a face painted with silver-gray patterns that seem to float independent of the features beneath, thin leather gloves that prevent any reflection of light from the hands, and no jewelry that could catch and reflect even the smallest glimmer.

Every Light Pill contains a secret encoded in its metadata, a phrase meant only for its holder, revealed during the ritual at precisely the right moment. The Silent Witness whispers that the observer becomes the observed, and in that moment of mutual recognition, both vanish into pure awareness. The Dream Weaver murmurs that dreams are not yours to possess but rather you are merely visiting them, a guest in landscapes that existed long before you arrived and will continue long after you depart. The River Singer confides that water remembers every shore it has ever touched, every stone it has ever worn smooth, every creature it has ever carried, and that those memories are available to anyone patient enough to listen. The Fire Keeper reveals that fire does not consume what it touches but rather transforms what was always waiting to become something else, that destruction is merely creation wearing a different face. The Shadow Dancer shares that shadows are not the absence of light but rather light's memory of where it has been, that darkness is not empty but full of all that light has left behind.

These messages are whispered from one participant to another during the rituals, passed like ancient secrets through generations that exist only in these twenty-nine nights, creating bonds that transcend the digital realm and persist long after the cycle completes. Those who have received such whispers report that they hear them again at unexpected moments, in the space between sleeping and waking, in moments of quiet contemplation, in times of crisis when ancient wisdom is most needed. The whispers become companions, guides, reminders that the world is more than it appears to be.

Before embarking on this journey, there are words of caution that must be spoken clearly. The creators of this project offer these artifacts as they are, without warranty or guarantee of any kind, assuming no responsibility for any outcomes that may result from deploying or playing this game. They accept no liability for any financial gains or losses that may occur through NFT activities, for any smart contract security issues or vulnerabilities that may emerge over time, for any IPFS content that may become unavailable as technologies change and services come and go, for any blockchain network issues that may prevent transactions from completing, for any legal or regulatory or tax implications that may arise in different jurisdictions, for any interactions between players that may lead to conflict or misunderstanding, or for any inaccuracies in metadata or game mechanics that may become apparent only after deployment.

By participating in this project, you acknowledge that you are responsible for deploying and managing your own smart contracts, that you alone must maintain your own IPFS content and ensure its continued availability, that you understand and accept the risks associated with blockchain technology and NFT markets, and that you participate entirely at your own risk with no recourse to anyone else should anything go wrong. This is the path of the solitary seeker, the one who takes full responsibility for their own journey. The tools are given freely, but the work is yours alone.

Twenty-nine nights await those who are brave enough to begin. Twenty-nine transformations are possible for those who complete the full cycle. One journey exists at the intersection of code and spirit, of blockchain and belief, of the digital and the divine, waiting for someone to step onto the path and see where it leads. The Light Pills await in their repository, ready to be deployed by whoever feels the call. The rituals are written in their metadata, waiting to be performed by those who understand that some things cannot be experienced through screens alone. The nights are numbered, each one unique, each one essential, each one offering something that cannot be found anywhere else in all the vast expanse of human experience.

The unknown is calling, as it has always called to those who can hear its voice beneath the noise of ordinary life. The question is not whether the Light Pills work or whether the rituals have power or whether the transformations are real. The question is whether you are ready to take the first pill, to begin the cycle, to discover for yourself what lies at the end of twenty-nine nights of deliberate, intentional, mystical exploration.

Are you ready?

The repository stands open. The artifacts await. The cycle has not yet begun, but it could begin tonight, with you, if you choose to answer the call that has brought you this far.

Enter if you dare. The unknown is waiting.`;

  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        className="fixed bottom-6 right-6 p-2 hover:scale-110 transition-transform opacity-30 hover:opacity-70 z-50"
        title="The Light Pill Prophecy"
      >
        <Pill className="h-5 w-5 text-green-500" strokeWidth={1.5} />
      </button>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto bg-black/95 border-green-500/30 border-2">
          <DialogHeader>
            <DialogTitle className="font-gothic text-2xl text-green-400 neon-glow">
              The Light Pill Prophecy
            </DialogTitle>
          </DialogHeader>
          <div className="prose prose-invert prose-sm max-w-none">
            <div className="text-foreground/90 leading-relaxed whitespace-pre-wrap text-sm font-light">
              {prophecyText}
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
